  version: '3.3'

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=eblooqsdb
      - MYSQL_USERNAME=admin
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ./post_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_USERNAME= root
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql